const Images = {
    res: require('../assets/Images/res.jpg'),
    res1: require('../assets/Images/res1.jpg'),
    res5: require('../assets/Images/res5.jpg'),   
    res3: require('../assets/Images/res3.jpg'),
    res4: require('../assets/Images/res4.jpg'),

    back: require('../assets/Images/back.png'),
    check: require('../assets/Images/check.png'),
    home: require('../assets/Images/home.png'),   
    search: require('../assets/Images/search.png'),
    user: require('../assets/Images/user.png'),
    plus: require('../assets/Images/plus.png'),
    info: require('../assets/Images/info.png'),
    filter: require('../assets/Images/filter.png'),
    star: require('../assets/Images/star.png'),
    settings: require('../assets/Images/settings.png'),
    web: require('../assets/Images/web.png'),
    profile: require('../assets/Images/profile.jpg'),
    man: require('../assets/Images/man.jpg'),
    friends: require('../assets/Images/friends.png'),
    close: require('../assets/Images/close.png'),

    upload1: require('../assets/Images/upload1.png'),
    photo: require('../assets/Images/photo.png'),
    users: require('../assets/Images/users.png'),
    frnds: require('../assets/Images/frnds.png'),
    logout: require('../assets/Images/logout.png'),
    target: require('../assets/Images/target.png'),
    upload: require('../assets/Images/upload.png'),
    refresh: require('../assets/Images/refresh.png'),
    folder: require('../assets/Images/folder.png'),
    editing: require('../assets/Images/editing.png'),
}
export default Images;